version: '3.9'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stats-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "9091:8080"
    environment:
      API_URL: http://localhost:9090/v3/api-docs

volumes:
  pgdata:





#services:
#  stats-server:
#    build: ./stat-service/stat-server
#    ports:
#      - "9090:9090"
#    depends_on:
#      - stats-db
#
#  stats-db:
#    image: postgres:16.1
#    environment:
#      POSTGRES_DB: stats
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 12345
#    ports:
#      - "5432:5432"
#
#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1